name: Feature Request
description: Suggest an idea
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What pain point does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed API
      placeholder: e.g. client.send_poll_message(...)
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
