name: Upload Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . pytest pytest-asyncio requests

    - name: Run tests
      run: pytest tests/

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v2.0.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}